# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dmv_driver_test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QLabel

from XMLParser import XMLParser


class Ui_DmvTestMainWindow(object):
    def __init__(self, questions, choiceimagequestions, choicequestions):
        super().__init__()
        self.indexLayoutWidget = None
        self.imageFrame = None
        self.imageLayout = None
        self.imageLayoutWidget = None
        self.choiceForm = None
        self.choiceLayout = None
        self.centralWidget = None
        self.statusbar = None
        self.menubar = None
        self.questions = questions
        self.choiceimagequestions = choiceimagequestions
        self.choicequestions = choicequestions
        self.current_question_index = 0
        self.correct_answers = 0
        self.questionLabel = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        question = self.questions[self.current_question_index]
        questiontext = question.question_text
        choiceimagequestion = self.choiceimagequestions[self.current_question_index]
        choicequestion = self.choicequestions[self.current_question_index]



        print(questiontext)

        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")

        self.QuestionLabel(questiontext)
        self.setupChoiceLayout()
        self.setupImageLayout()
        self.setupIndexLayout(self.centralWidget)
        self.setupNavigationLayout(self.centralWidget)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)

        MainWindow.setMenuBar(self.menubar)
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def QuestionLabel(self, questionText):

        font = QtGui.QFont()
        font.setPointSize(12)

        self.questionLabel = QtWidgets.QLabel(self.centralWidget)
        self.questionLabel.setGeometry(QtCore.QRect(20, 280, 750, 30))  # Adjust geometry as needed
        self.questionLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.questionLabel.setObjectName("questionLabel")
        self.questionLabel.setText(questionText)
        self.questionLabel.setFont(font)

    def setupChoiceLayout(self):
        self.choiceLayout = QtWidgets.QGroupBox(self.centralWidget)
        self.choiceLayout.setGeometry(QtCore.QRect(20, 310, 750, 150))
        self.choiceLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.choiceLayout.setObjectName("choiceLayout")
        self.choiceForm = QtWidgets.QFormLayout(self.choiceLayout)

        for i in range(1, 5):
            self.addChoice(f"ch_button_{i}")

    def addChoice(self, radioButtonName):
        radioButton = QtWidgets.QRadioButton(self.choiceLayout)
        radioButton.setObjectName(radioButtonName)
        setattr(self, radioButtonName, radioButton)  # Store the radioButton as an attribute

        self.choiceForm.addRow(radioButton)

    def setupImageLayout(self):
        self.imageLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.imageLayoutWidget.setGeometry(QtCore.QRect(19, 19, 761, 231))
        self.imageLayout = QtWidgets.QVBoxLayout(self.imageLayoutWidget)
        self.imageFrame = QtWidgets.QFrame(self.imageLayoutWidget)
        self.imageLayout.addWidget(self.imageFrame)

    def setupIndexLayout(self, parent):
        self.indexLayoutWidget = QtWidgets.QWidget(parent)
        font = QtGui.QFont()
        font.setPointSize(12)

        self.numCorrect = QtWidgets.QLabel(self.indexLayoutWidget)
        self.numCorrect.setGeometry(QtCore.QRect(200, 515, 100, 50))
        self.numCorrect.setFont(font)
        self.numCorrect.setText("Correct: {}/40".format(self.correct_answers))

        self.currentIndex = QtWidgets.QLabel(self.indexLayoutWidget)
        self.currentIndex.setGeometry(QtCore.QRect(50, 515, 150, 50))
        self.currentIndex.setFont(font)
        self.currentIndex.setText("Question {} of 40".format(self.current_question_index + 1))


        self.separator = QtWidgets.QFrame(self.indexLayoutWidget)
        self.separator.setFrameShape(QtWidgets.QFrame.VLine)
        self.separator.setGeometry(QtCore.QRect(60, 530, 250, 20))

    def setupNavigationLayout(self, parent):

        font = QtGui.QFont()
        font.setPointSize(12)

        self.nextButton = QtWidgets.QPushButton(parent)
        self.nextButton.setGeometry(QtCore.QRect(575, 525, 200, 30))
        self.nextButton.setFont(font)
        self.nextButton.setText("Next Question")
        self.nextButton.clicked.connect(self.next)

        self.quitButton = QtWidgets.QPushButton(parent)
        self.quitButton.setGeometry(QtCore.QRect(375, 525, 200, 30))
        self.quitButton.setFont(font)
        self.quitButton.setText("Quit Quiz")
        self.quitButton.clicked.connect(QApplication.quit)

    def next(self):
        if self.current_question_index < 39:
            self.current_question_index = self.current_question_index + 1
            self.setupUi(MainWindow)
        else:
            print("Quiz Completed!")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    xml_parser = XMLParser()    # Create the XML parser.

    result = xml_parser.parse("florida_drivers_test.xml")   # Parse the XML file.
    questions = result[0]   # Get the questions.
    choiceimagequestions = result[1]
    choicequestions = result[2]

    ui = Ui_DmvTestMainWindow(questions,
                              choiceimagequestions,
                              choicequestions)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
